apiVersion: v1
name: echart-funnel
version: 1.0
appVersion: 1.0.0
icon: http://echart-logo.os.cecii.cn/funnel.ico
keywords: 
  - echarts
  - funnel
  - 漏斗图
description: 本应用是供Java开发使用的ECharts的报表公共组件的漏斗图组件