apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.fullname" . }}
    helm.sh/chart: {{ include "mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: a-{{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          {{- if .Values.volumes }}
          volumeMounts: 
            {{- range $index, $volume := .Values.volumes }}
            - name: v-{{ $index }}
              mountPath: {{ $volume.mountPath }}
            {{- end }}             
          {{- end }}
      {{- if .Values.volumes }}
      volumes: 
        {{- range $index, $volume := .Values.volumes }}
        - name: v-{{ $index }}
          persistentVolumeClaim:
            claimName: {{ include "mychart.fullname" $ }}-pvc-{{ $index }}
        {{- end }}
      {{- end -}}
