{{ if .Values.volumes }}
{{- range $index, $volume := .Values.volumes -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" $ }}-pvc-{{ $index }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.fullname" $ }}-pvc-{{ $index }}
    helm.sh/chart: {{ include "mychart.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.size }}
  selector:
      matchLabels:
        app.kubernetes.io/name: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
  volumeName: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
---
{{ end }}
{{ end }}
